version: "3.8"

services:
  compiler:
    platform: linux/amd64   # ← 追加
    build:
      context: .
      dockerfile: Dockerfile
    container_name: compilerbook
    volumes:
      - ./9cc:/9cc
    working_dir: /9cc
    stdin_open: true
    tty: true